# Generated by Django 4.2.7 on 2023-11-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_premedicalform_age_premedicalform_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premedicalform',
            name='disorders_diagnosed',
            field=models.TextField(blank=True),
        ),
    ]
